added jsx-a11y and added some a11y updates to the site
react-rally/react-rally-2019 pull request #8
Opened 2019-05-24 23:41 UTC by johnnyxbell

2019-07-22 17:19 UTC, mzabriskie requested changes
Couple changes suggested as well as a rebase required to merge.

Thanks for the PR!

2019-07-22 17:19 UTC, mzabriskie commented on app/components/Header.js
> +        <Icon href="https://twitter.com/ReactRally" type="React Rally Twitter" />
The `<Icon />` component expects `type` prop to be something that can be used for it's icon resource. I would suggest keeping `type` as it was, and internal to `<Icon />` add `aria-label="React Rally ${type}"`.

2019-07-22 17:19 UTC, mzabriskie commented on app/screens/Schedule/index.js
>            href="javascript://"
The `href` prop is no longer needed.

2020-09-29 17:13 UTC, closed without merging

2020-09-29 17:13 UTC, johnnyxbell commented
Old PR no longer required.